### PR TITLE
A couple of typos fixed and a few full stops for consistency.

### PR DESCRIPTION
**Pull request by tonyhaddon**
Hi,

First PR ever. I hope I'm doing this right. Please let me know if there's additional information I need to provide here.

I've seen that this file is the same across many starterkits. Is there a specific way to propagate this if all those repos want these changes, or should I do a PR on each of them?

### CODE REVIEW

**Comment by bradfrost** [comment]
Thanks so much, @tonyhaddon! You did indeed do it right. Really appreciate it!

**Comment by tonyhaddon** [comment]
Just on that last question... any guidance?

> Is there a specific way to propagate this if all those repos want these changes, or should I do a PR on each of them?

**Comment by bradfrost** [comment]
@tonyhaddon alas, it's a manual effort as each repo is using its own file extension (i.e. `.mustache`, `.twig`, `.hbs`, etc). It should hopefully be an easy copy/paste job but yeah involves a bit of manual work.

Thanks again for this!

**Comment by tonyhaddon** [comment]
No worries, I’ll take a look at it.

**Pull request merged**
